# Generated by Django 5.0.4 on 2024-04-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_statuc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='statuc',
            new_name='status',
        ),
    ]
